### ISSUE TITLE
Backpack - Not Useable

### ISSUE THREAD

**Issue by lifeofsenpai** [TheUnknownPerson/BetterStorage#1]
Hello, and thank you for looking into my issue. I am using Better Storage V. 1.012 and I am unable to use the backpack. It shows up as a block with purple and black checkered squares. I understand this is probably dude to not having a model or missing a texture. I am also unable to place it, put it in my armor slot, open it, or generally do anything with. Thanks again.

**Comment by TheUnknownPerson** [comment]
Hey, thank you for reporting this issue!
I know this bug ...
I'm currently working to fix a lot of bugs in this mod.

This is the wrong repository for reporting issues and yes I know the link to this repository is on the thread.
I forgot to update this link. I just updated the link right now.
I will recreate this repository after the mod goes to the beta stage.

There are alot of bugs in the build. I'm currently working to fix the reinforced chests and lockers.
If you report an issue in the dev repository, I will try to fix the reported issue faster.

Maybe you will report this issue in the dev repository:
https://github.com/TheUnknownPerson/BetterStorage-1.8.9

Thank you!
